services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "your_secret_key_here"
    volumes:
      - .:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && gunicorn --bind 0.0.0.0:5000 'app:create_app()'"
