version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bee_mgmt
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
